#!/usr/bin/env python3
"""Build index.html from the data files and the HTML template.

Single source of truth:
  stadiums_proposed.csv  -> the venue list (the map)
  team_travel.csv        -> per-team group-stage travel (the dumbbell chart)

team_travel.csv is generated by team_travel.py. Regenerate it when the
schedule or venues change, then run this.

Usage:  python build.py
"""
import csv, json, os

HERE = os.path.dirname(os.path.abspath(__file__))


def read_csv(name):
    with open(os.path.join(HERE, name), newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def build_venues(stadiums):
    venues = []
    for r in stadiums:
        proposed = int(r["is_proposed_venue"])
        venues.append({
            "id": int(r["stadium_id"]),
            "name": r["stadium_name"],
            "city": r["city"],
            "country": r["country"],
            "lat": round(float(r["lat"]), 4),
            "lon": round(float(r["lon"]), 4),
            "capacity": int(r["capacity"]),
            "actual": int(r["is_current_venue"]),
            "proposed": proposed,
            "round": r["proposed_round"] if proposed else "actual_only",
            "group": r["hosted_group"],
        })
    return venues


def build_travel(travel_rows, coord_by_id):
    by_team = {}
    for r in travel_rows:
        by_team.setdefault(r["team_name"], {})[r["scenario"]] = r

    def legs_for(r):
        ids = [r["game_1_stadium_id"], r["game_2_stadium_id"], r["game_3_stadium_id"]]
        cities = [r["game_1_stadium"], r["game_2_stadium"], r["game_3_stadium"]]
        coords = [coord_by_id[i] for i in ids]
        legs = [round(float(r["game_1_to_2_km"]), 1), round(float(r["game_2_to_3_km"]), 1)]
        return cities, coords, legs, round(float(r["total_km"]), 1)

    out = []
    for team, sc in by_team.items():
        pc, pco, pl, pk = legs_for(sc["proposed"])
        ac, aco, al, ak = legs_for(sc["actual"])
        out.append({
            "team": team,
            "group": sc["proposed"]["group_id"],
            "proposed_km": pk, "proposed_route": " \u2192 ".join(pc),
            "proposed_legs": pl, "proposed_coords": pco, "proposed_cities": pc,
            "actual_km": ak, "actual_route": " \u2192 ".join(ac),
            "actual_legs": al, "actual_coords": aco, "actual_cities": ac,
        })
    return out


def main():
    stadiums = read_csv("stadiums_proposed.csv")
    travel_rows = read_csv("team_travel.csv")
    coord_by_id = {r["stadium_id"]: [round(float(r["lon"]), 4), round(float(r["lat"]), 4)]
                   for r in stadiums}

    venues = build_venues(stadiums)
    travel = build_travel(travel_rows, coord_by_id)

    with open(os.path.join(HERE, "index.template.html"), encoding="utf-8") as f:
        html = f.read()
    html = html.replace("__TRAVEL_DATA__", json.dumps(travel, ensure_ascii=False, separators=(",", ":")))
    html = html.replace("__VENUES__", json.dumps(venues, ensure_ascii=False, separators=(",", ":")))

    out_path = os.path.join(HERE, "index.html")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"Wrote {out_path}  ({len(venues)} venues, {len(travel)} teams)")


if __name__ == "__main__":
    main()
